// Copyright 2022 Taro Hayashi (@w_vwbw)
// SPDX-License-Identifier: GPL-2.0-or-later
//  make tarohayashi/onthe15:hilo

#include QMK_KEYBOARD_H
#include "lib/add_keycodes.h"

#define KANA KC_LNG1
#define EISU KC_LNG2

// CMD + CTL
#define CC_T(kc) MT(MOD_LGUI | MOD_LCTL, kc)

// SHIFT + CTL
#define SC_T(kc) MT(MOD_LCTL | MOD_LCTL, kc)

enum layer_names {
  BASE = 0,
  TEN_KEY = 1,
  RAISE = 2,
  LOWER = 3,
//  LIGHT = 5,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [BASE] = LAYOUT(
      CC_T(KC_ESC), KC_Q,    KC_W,    KC_E,    KC_R,              KC_T,           /**/ LT(RAISE, EISU),   XXXXXXX,           LT(RAISE, KANA),   /**/  KC_Y,           KC_U,            KC_I,    KC_O,     CC_T(KC_P), KC_BSPC,
      SC_T(KC_TAB), KC_A,    KC_S,    KC_D,    LT(TEN_KEY, KC_F), KC_G,           /**/ LT(RAISE, KC_SPC), UG_TOGG,           LT(RAISE, KC_SPC), /**/  KC_H,           KC_J,            KC_K,    KC_L,     KC_SCLN,    KC_ENT,
      KC_LSFT,      KC_Z,    KC_X,    KC_C,    KC_V,              KC_B,           /**/ LT(LOWER, KC_SPC), KC_GRV,            LT(LOWER, KC_SPC), /**/  KC_N,           KC_M,            KC_COMM, KC_DOT,   KC_SLSH,    KC_GRV,
      KC_LCTL,      KC_LGUI, KC_LALT, KC_LCTL, LT(LOWER, EISU),   SGUI_T(KC_SPC), /**/ SGUI_T(KC_SPC),    LT(LOWER, KC_SPC), SGUI_T(KC_SPC),    /**/  SGUI_T(KC_SPC), LT(RAISE, KANA), KC_LEFT, KC_DOWN,  KC_UP,      KC_RGHT
    ),
    [TEN_KEY] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX,  /**/ XXXXXXX, KC_7, KC_8, KC_9,   KC_0,    KC_DEL,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX,  /**/ XXXXXXX, KC_4, KC_5, KC_6,   KC_RGHT, KC_ENT,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX,  /**/ XXXXXXX, KC_1, KC_2, KC_3,   XXXXXXX, KC_QUOT,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX,  /**/ KC_0,    KC_0, KC_0, KC_DOT, XXXXXXX, XXXXXXX
    ),
    [RAISE] = LAYOUT(
      KC_TILD,  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, /**/ KC_UNDS, XXXXXXX, KC_PLUS, /**/ KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE,
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_QUOT,
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, KC_LT,   KC_GT,   KC_QUES, KC_BSLS,
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
    ),
    [LOWER] = LAYOUT(
      KC_TILD,  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, /**/ KC_UNDS, XXXXXXX, KC_PLUS, /**/ KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE,
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, S(KC_QUOT),
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, KC_LT,   KC_GT,   KC_QUES, KC_BSLS,
      XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, /**/ XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
    ),
};

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [BASE] =   {
        ENCODER_CCW_CW(KC_A, KC_B),
        ENCODER_CCW_CW(KC_C, KC_D),
        ENCODER_CCW_CW(UG_HUEU, UG_HUED),
        ENCODER_CCW_CW(KC_G, KC_H)
        },
    [TEN_KEY] = {
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX)
        },
    [RAISE] = {
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX)
        },
    [LOWER] = {
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX),
        ENCODER_CCW_CW(XXXXXXX, XXXXXXX)
        }
};

